base: "configs/config.yaml"

training:
  epochs: 5
  lr: 0.005

model:
  exp: "MU02"

data:
  target_format: "counts"
  augment: True
  classes:
  - "bicycle"
  - "motorcycle"
  - "vehicle"

unlearning:
  method: "sebastian_unlearn"
  amount: 0.95
  rand_init: False

wandb:
  enabled: True
  tags:
    - MU
    - MSE
    - Human
    - single_count
    - sebastian
    - "95"
    - resilient-tree-3