base: "configs/config.yaml"

training:
  epochs: 3
  lr: 0.0005

model:
  exp: "MU02"

data:
  target_format: "counts"
  augment: True
  classes:
  - "human"

unlearning:
  method: "fine_tune"

wandb:
  enabled: True
  tags:
    - MU
    - MSE
    - Human
    - single_count
    - fine_tune
    - resilient-tree-3