base: ""

training:
  epochs: 20
  lr: 0.1
  batch_size: 16
  log_freq: 500 #Number of batches
  loss: "mse"

evaluation:
  metrics:
  - "rmse"
  - "mae"
  val_per_epoch: 15

model:
  arch: "resnet50d" 
  task: "counter"
  exp: "Baseline_all_classes"

data:
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  augment: True
  root: "/Data/Harborfront_raw/"
  train: "/Data/Harborfront_raw/repai/aug_Train_data.csv"
  valid: "/Data/Harborfront_raw/repai/Valid_data.csv"
  test: "/Data/Harborfront_raw//repai/Test_data.csv"
  target_format: 'counts'

wandb:
  enabled: True
  plotting: True
  resume: null
  project_name: "MU+XAI Workshop"
  entity: "repai"
  tags:
    - Baseline
    - Augmentation

unlearning: