base: ""

training:
  epochs: 20
  lr: 0.1
  lr_steps: 5000
  lr_decay: 0.1
  batch_size: 48
  validation_steps: 10000
  loss: "huber"

evaluation:
  metrics:
  - "rmse"
  - "mae"

model:
  arch: "resnet50d" 
  task: "counter"
  exp: "Baseline01 - Huber Loss"

data:
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"
  root: "/Data/Harborfront_raw/"
  train: "/Data/Harborfront_raw/repai/Train_data.csv"
  valid: "/Data/Harborfront_raw/repai/Valid_data.csv"
  test: "/Data/Harborfront_raw//repai/Test_data.csv"
  target_format: 'multilabel_counts'


wandb:
  enabled: True
  plotting: True
  resume: False
  log_freq: 500 #Number of batches
  project_name: "MU+XAI Workshop"
  entity: "repai"
  tags:
    - Baseline