base: "configs/config.yaml"

training:
  epochs: 10
  lr: 0.1
  lr_steps: 5000
  lr_decay: 0.101
  batch_size: 16
  log_freq: 500 #Number of batches
  loss: "mse"

model:
  exp: "MU01"

data:
  target_format: "multilabel_counts"
  augment: False
  classes:
  - "human"
  - "bicycle"
  - "motorcycle"
  - "vehicle"

unlearning:
  noise_scale: 0.1
  noise_scale_2: 0.01
  epochs_2: 10
  transpose: False
  reinit_last: False
  add_noise: False  
  train_dense: True
  train_kernel: False
  train_bias: False
  train_last: True
  class_to_forget: "human"
  type: "skip"
  method: "sebastian_unlearn"

wandb:
  enabled: True
  tags:
    - MU
    - sebastian
    - Skip
    - Human
    - MSE
    - '4'
    - resilient-tree-3
    - multi_count
    - Pruning
    # - Finetuning
    # - Trans
    # - Kernel
    # - Dense
    # - Reinit_last
    # - confusion