base: config.yaml

model:
  classes:
  - "human"
  name: "ResNet56_human_hires"
  exp: "baseline01"

data:
  root: "/Data/Harborfront_raw/"
  train: "data/Train_data.csv"
  valid: "data/Valid_data.csv"
  test: "data/Test_data.csv"
  im_size: 
  - 320
  - 320
  - 3
  binary_cls: True

wandb:
  log_freq: 400 #Number of batches